apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: ghcr.io/jyoti857/backend:latest

          env:
            - name: REDIS_HOST
              value: redis

          ports:
            - containers: 3000

          livenessProbe:
            httpGet:
              path: /health
              port: 3000

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
